---
title: "Título Análisis de Precios"
output:
  html_document:
    theme: flatly
    toc: true
    toc_float: true
    highlight: tango
    number_sections: true
    self_contained: true
---

# Análisis de precios 2024
```{r setup, include=FALSE}
library(tidyverse)
library(readr)

library(knitr)
library(kableExtra)
````


En el siguiente apartado, creamos una tabla con formato html

```{r mostrar-datos1, echo=FALSE}
# Ejemplo con un data frame
datos <- head(mtcars)
knitr::kable(datos,format = "html", caption = "Tabla de datos de mtcars")%>%
  kable_styling(bootstrap_options = c("striped", "hover"), full_width = F)


````

Esta tabla especifica que el color de la primera fila de la tabla es de un color especifico:



```{r mostrar-datos2, echo=FALSE}
library(knitr)
library(kableExtra)

# Ejemplo con un data frame
datos <- head(mtcars)
knitr::kable(datos, format = "html", caption = "Tabla de datos de mtcars") %>%
  kable_styling(bootstrap_options = c("striped", "hover"), full_width = FALSE) %>%
  row_spec(0, background = "#e6d194", color = "black")  # 🔵 Encabezado azul con texto blanco
````



# Carga de datos (ajusta la ruta según tu archivo)
```{r mostrar-datos3, echo=TRUE}
datos <- read_csv("datos/precios_2024.csv")
head(datos)


# Vista general de los datos
summary(datos)


````


